-- supabase
create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 30),
  message text not null check (char_length(message) <= 180),
  created_at timestamptz not null default now()
);

create index if not exists guestbook_messages_created_at_idx
  on public.guestbook_messages (created_at desc);

alter table public.guestbook_messages enable row level security;

drop policy if exists "guestbook_select_public" on public.guestbook_messages;
drop policy if exists "guestbook_insert_public" on public.guestbook_messages;
drop policy if exists "guestbook_delete_admin" on public.guestbook_messages;

-- public can read all messages.
create policy "guestbook_select_public"
  on public.guestbook_messages
  for select
  using (true);

-- public can insert messages.
create policy "guestbook_insert_public"
  on public.guestbook_messages
  for insert
  with check (true);

-- Only admin email can delete.
create policy "guestbook_delete_admin"
  on public.guestbook_messages
  for delete
  using ((auth.jwt() ->> 'email') = 'rninverse@gmail.com');
